---

name: windows

on:
  pull_request:

  push:
    branches:
      - master

jobs:
  test:
    runs-on: windows-2022

    strategy:
      fail-fast: false

      matrix:
        version: [2.5.8, 2.6.6, 2.7.2, head]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: .bundle
          key: gems-${{ hashFiles('**/Gemfile.lock') }}

      - uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          ruby-version: ${{ matrix.version }}

      - name: Patch rb-readline
        run: |
          git clone -q --depth=5  --no-tags --branch=byebug https://github.com/deivid-rodriguez/rb-readline.git C:\rb-readline
          $n_dir = $(ruby -e "print RbConfig::CONFIG['sitelibdir']")
          Copy-Item -Path C:\rb-readline\lib\* -Destination $n_dir -Recurse

      - name: Setup dependencies
        shell: bash
        run: bin/setup.sh

      - name: Run tests
        run: ruby bin/rake
        continue-on-error: ${{ matrix.version == 'head' }}

    timeout-minutes: 15
